listData = [{
	"name": "课堂实例",
	"iconOpen": "css/ztree.3.5.26//zTreeStyle/img/diy/1_open.png",
	"iconClose": "css/ztree.3.5.26//zTreeStyle/img/diy/1_close.png",
//	"open": true,
	"children": [{
		"name": "ch1-html,css,javasrcipt初体验",
		"children": [{
			"name": "test1",
			"url": "html/ch1/test1.html"
		}, {
			"name": "test2",
			"url": "html/ch1/test2.html"
		}, {
			"name": "test3",
			"url": "html/ch1/test3.html"
		}]
	}, {
		"name": "ch2-html标签一",
		"children": [{
			"name": "test1",
			"url": "html/ch2/test1.html"
		}, {
			"name": "test2",
			"url": "html/ch2/test2.html"
		}, {
			"name": "test3",
			"url": "html/ch2/test3.html"
		}, {
			"name": "test4",
			"url": "html/ch2/test4.html"
		}, {
			"name": "test6",
			"url": "html/ch2/test6.html"
		}, {
			"name": "test7",
			"url": "html/ch2/test7.html"
		}, {
			"name": "test8",
			"url": "html/ch2/test8.html"
		}, {
			"name": "test9",
			"url": "html/ch2/test9.html"
		}, {
			"name": "test10",
			"url": "html/ch2/test10.html"
		}, {
			"name": "test11",
			"url": "html/ch2/test11.html"
		}, {
			"name": "test12",
			"url": "html/ch2/test12.html"
		}, {
			"name": "test13",
			"url": "html/ch2/test13.html"
		}, {
			"name": "test14",
			"url": "html/ch2/test14.html"
		}]
	}, {
		"name": "ch3-html标签2",
		"children": [{
			"name": "test1",
			"url": "html/ch3/test1.html"
		}, {
			"name": "test2",
			"url": "html/ch3/test2.html"
		}, {
			"name": "test3",
			"url": "html/ch3/test3.html"
		}, {
			"name": "test4",
			"url": "html/ch3/test4.html"
		}, {
			"name": "test5",
			"url": "html/ch3/test5.html"
		}, {
			"name": "test6",
			"url": "html/ch3/test6.html"
		}, {
			"name": "test7",
			"url": "html/ch3/test7.html"
		}, {
			"name": "test8",
			"url": "html/ch3/test8.html"
		}, {
			"name": "test9",
			"url": "html/ch3/test9.html"
		}, {
			"name": "test10",
			"url": "html/ch3/test10.html"
		}, {
			"name": "test11",
			"url": "html/ch3/test11.html"
		}, {
			"name": "test12",
			"url": "html/ch3/test12.html"
		}, {
			"name": "test13",
			"url": "html/ch3/test13.html"
		}]
	}, {
		"name": "ch4-html标签3",
		"children": [{
			"name": "test1",
			"url": "html/ch4/test1.html"
		}, {
			"name": "test3",
			"url": "html/ch4/test3.html"
		}, {
			"name": "test4",
			"url": "html/ch4/test4.html"
		}, {
			"name": "test5",
			"url": "html/ch4/test5.html"
		}, {
			"name": "test6",
			"url": "html/ch4/test6.html"
		}, {
			"name": "test8",
			"url": "html/ch4/test8.html"
		}, {
			"name": "test9",
			"url": "html/ch4/test9.html"
		}, {
			"name": "test10",
			"url": "html/ch4/test10.html"
		}, {
			"name": "test11",
			"url": "html/ch4/test11.html"
		}]
	}, {
		"name": "ch5-css-选择器",
		"children": [{
			"name": "test1",
			"url": "html/ch5/test1.html"
		}, {
			"name": "test2",
			"url": "html/ch5/test2.html"
		}, {
			"name": "test3",
			"url": "html/ch5/test3.html"
		}, {
			"name": "test4",
			"url": "html/ch5/test4.html"
		}, {
			"name": "test5",
			"url": "html/ch5/test5.html"
		}, {
			"name": "test6",
			"url": "html/ch5/test6.html"
		}, {
			"name": "test7",
			"url": "html/ch5/test7.html"
		}, {
			"name": "test8",
			"url": "html/ch5/test8.html"
		}, {
			"name": "test9",
			"url": "html/ch5/test9.html"
		}, {
			"name": "test10",
			"url": "html/ch5/test10.html"
		}, {
			"name": "test11",
			"url": "html/ch5/test11.html"
		}, {
			"name": "test12",
			"url": "html/ch5/test12.html"
		}, {
			"name": "test13",
			"url": "html/ch5/test13.html"
		}, {
			"name": "test14",
			"url": "html/ch5/test14.html"
		}, {
			"name": "test15",
			"url": "html/ch5/test15.html"
		}, {
			"name": "test16",
			"url": "html/ch5/test16.html"
		}, {
			"name": "test17",
			"url": "html/ch5/test17.html"
		}, {
			"name": "test18",
			"url": "html/ch5/test18.html"
		}]
	}, {
		"name": "ch6-css-文字,盒子模型",
		"children": [{
			"name": "test1",
			"url": "html/ch6/test1.html"
		}, {
			"name": "test2",
			"url": "html/ch6/test2.html"
		}, {
			"name": "test3",
			"url": "html/ch6/test3.html"
		}, {
			"name": "test4",
			"url": "html/ch6/test4.html"
		}, {
			"name": "test5",
			"url": "html/ch6/test5.html"
		}, {
			"name": "test6",
			"url": "html/ch6/test6.html"
		}, {
			"name": "test7",
			"url": "html/ch6/test7.html"
		}, {
			"name": "test8",
			"url": "html/ch6/test8.html"
		}, {
			"name": "test9",
			"url": "html/ch6/test9.html"
		}, {
			"name": "test10",
			"url": "html/ch6/test10.html"
		}, {
			"name": "test11",
			"url": "html/ch6/test11.html"
		}, {
			"name": "test12",
			"url": "html/ch6/test12.html"
		}, {
			"name": "test13",
			"url": "html/ch6/test13.html"
		}, {
			"name": "test14",
			"url": "html/ch6/test14.html"
		}, {
			"name": "test15",
			"url": "html/ch6/test15.html"
		}, {
			"name": "test16",
			"url": "html/ch6/test16.html"
		}, {
			"name": "test17",
			"url": "html/ch6/test17.html"
		}, {
			"name": "test18",
			"url": "html/ch6/test18.html"
		}, {
			"name": "test18",
			"url": "html/ch6/test19.html"
		}]
	}, {
		"name": "ch7-css-布局，小技巧",
		"children": [{
			"name": "test2",
			"url": "html/ch7/test2.html"
		}, {
			"name": "test3",
			"url": "html/ch7/test3.html"
		}, {
			"name": "test4",
			"url": "html/ch7/test4.html"
		}, {
			"name": "test6",
			"url": "html/ch7/test6.html"
		}, {
			"name": "test7",
			"url": "html/ch7/test7.html"
		}, {
			"name": "test8",
			"url": "html/ch7/test8.html"
		}, {
			"name": "test9",
			"url": "html/ch7/test9.html"
		}, {
			"name": "test10",
			"url": "html/ch7/test10.html"
		}, {
			"name": "test11",
			"url": "html/ch7/test11.html"
		}, {
			"name": "test12",
			"url": "html/ch6/test12.html"
		}, {
			"name": "test13",
			"url": "html/ch7/test13.html"
		}, {
			"name": "test14",
			"url": "html/ch7/test14.html"
		}, {
			"name": "test15",
			"url": "html/ch7/test15.html"
		}, {
			"name": "test16",
			"url": "html/ch7/test16.html"
		}, {
			"name": "test17",
			"url": "html/ch7/test17.html"
		}, {
			"name": "test18",
			"url": "html/ch7/test18.html"
		}, {
			"name": "test19",
			"url": "html/ch7/test19.html"
		}, {
			"name": "test20",
			"url": "html/ch7/test20.html"
		}, {
			"name": "test21",
			"url": "html/ch7/test21.html"
		}, {
			"name": "test22",
			"url": "html/ch7/test22.html"
		}, {
			"name": "test23",
			"url": "html/ch7/test23.html"
		}]
	}, {
		"name": "ch8-css-经典布局",
		"children": [{
			"name": "test1",
			"url": "html/ch8/test1.html"
		}, {
			"name": "test2",
			"url": "html/ch8/test2.html"
		}, {
			"name": "test3",
			"url": "html/ch8/test3.html"
		}, {
			"name": "test4",
			"url": "html/ch8/test4.html"
		}, {
			"name": "test5",
			"url": "html/ch8/test5.html"
		}, {
			"name": "test6",
			"url": "html/ch8/test6.html"
		}, {
			"name": "test7",
			"url": "html/ch8/test7.html"
		}]
	}, {
		"name": "ch9-javascript很强大",
		"children": [{
			"name": "test1",
			"url": "html/ch9/test1.html"
		}, {
			"name": "test2",
			"url": "html/ch9/test2.html"
		}, {
			"name": "test3",
			"url": "html/ch9/test3.html"
		}, {
			"name": "test4",
			"url": "html/ch9/test4.html"
		}, {
			"name": "test5",
			"url": "html/ch9/test5.html"
		}, {
			"name": "test6",
			"url": "html/ch9/test6.html"
		}, {
			"name": "test7",
			"url": "html/ch9/test7.html"
		}, {
			"name": "test8",
			"url": "html/ch9/test8.html"
		}, {
			"name": "test9",
			"url": "html/ch9/test9.html"
		}, {
			"name": "test10",
			"url": "html/ch9/test10.html"
		}, {
			"name": "test11",
			"url": "html/ch9/test11.html"
		}, {
			"name": "test12",
			"url": "html/ch9/test12.html"
		}, {
			"name": "test13",
			"url": "html/ch9/test13.html"
		}, {
			"name": "test14",
			"url": "html/ch9/test14.html"
		}, {
			"name": "test15",
			"url": "html/ch9/test15.html"
		}, {
			"name": "test16",
			"url": "html/ch9/test16.html"
		}]
	}, {
		"name": "ch10-javascript-基础",
		"children": [{
			"name": "test1",
			"url": "html/ch10/test1.html"
		}, {
			"name": "test2",
			"url": "html/ch10/test2.html"
		}, {
			"name": "test3",
			"url": "html/ch10/test3.html"
		}, {
			"name": "test4",
			"url": "html/ch10/test4.html"
		}, {
			"name": "test5",
			"url": "html/ch10/test5.html"
		}, {
			"name": "test6",
			"url": "html/ch10/test6.html"
		}, {
			"name": "test7",
			"url": "html/ch10/test7.html"
		}, {
			"name": "test8",
			"url": "html/ch10/test8.html"
		}, {
			"name": "test9",
			"url": "html/ch10/test9.html"
		}, {
			"name": "test10",
			"url": "html/ch10/test10.html"
		}, {
			"name": "test11",
			"url": "html/ch10/test11.html"
		}, {
			"name": "test12",
			"url": "html/ch10/test12.html"
		}, {
			"name": "test13",
			"url": "html/ch10/test13.html"
		}, {
			"name": "test14",
			"url": "html/ch10/test14.html"
		}, {
			"name": "test15",
			"url": "html/ch10/test15.html"
		}, {
			"name": "test16",
			"url": "html/ch10/test16.html"
		}, {
			"name": "test17",
			"url": "html/ch10/test17.html"
		}, {
			"name": "test18",
			"url": "html/ch10/test18.html"
		}, {
			"name": "test19",
			"url": "html/ch10/test19.html"
		}, {
			"name": "test20",
			"url": "html/ch10/test20.html"
		}, {
			"name": "test21",
			"url": "html/ch10/test21.html"
		}]
	}, {
		"name": "ch11-javascript-数组与流程控制",
		"children": [{
			"name": "test1",
			"url": "html/ch11/test1.html"
		}, {
			"name": "test2",
			"url": "html/ch11/test2.html"
		}, {
			"name": "test3",
			"url": "html/ch11/test3.html"
		}, {
			"name": "test4",
			"url": "html/ch11/test4.html"
		}, {
			"name": "test5",
			"url": "html/ch11/test5.html"
		}, {
			"name": "test6",
			"url": "html/ch11/test6.html"
		}, {
			"name": "test7",
			"url": "html/ch11/test7.html"
		}, {
			"name": "test8",
			"url": "html/ch11/test8.html"
		}, {
			"name": "test9",
			"url": "html/ch11/test9.html"
		}, {
			"name": "test10",
			"url": "html/ch11/test10.html"
		}, {
			"name": "test11",
			"url": "html/ch11/test11.html"
		}, {
			"name": "test12",
			"url": "html/ch11/test12.html"
		}, {
			"name": "test13",
			"url": "html/ch11/test13.html"
		}, {
			"name": "test14",
			"url": "html/ch11/test14.html"
		}, {
			"name": "test15",
			"url": "html/ch11/test15.html"
		}, {
			"name": "test16",
			"url": "html/ch11/test16.html"
		}, {
			"name": "test17",
			"url": "html/ch11/test17.html"
		}, {
			"name": "test18",
			"url": "html/ch11/test18.html"
		}]
	}, {
		"name": "ch12-javascript-函数与事件",
		"children": [{
			"name": "test1",
			"url": "html/ch12/test1.html"
		}, {
			"name": "test2",
			"url": "html/ch12/test2.html"
		}, {
			"name": "test3",
			"url": "html/ch12/test3.html"
		}, {
			"name": "test4",
			"url": "html/ch12/test4.html"
		}, {
			"name": "test5",
			"url": "html/ch12/test5.html"
		}, {
			"name": "test6",
			"url": "html/ch12/test6.html"
		}, {
			"name": "test8",
			"url": "html/ch12/test8.html"
		}, {
			"name": "test9",
			"url": "html/ch12/test9.html"
		}, {
			"name": "test10",
			"url": "html/ch12/test10.html"
		}, {
			"name": "test11",
			"url": "html/ch12/test11.html"
		}, {
			"name": "test12",
			"url": "html/ch12/test12.html"
		}, {
			"name": "test13",
			"url": "html/ch12/test13.html"
		}, {
			"name": "test14",
			"url": "html/ch12/test14.html"
		}, {
			"name": "test15",
			"url": "html/ch12/test15.html"
		}, {
			"name": "test16",
			"url": "html/ch12/test16.html"
		}]
	}, {
		"name": "ch13-javascript-内置对象",
		"children": [{
			"name": "test1",
			"url": "html/ch13/test1.html"
		}, {
			"name": "test2",
			"url": "html/ch13/test2.html"
		}, {
			"name": "test3",
			"url": "html/ch13/test3.html"
		}, {
			"name": "test4",
			"url": "html/ch13/test4.html"
		}, {
			"name": "test5",
			"url": "html/ch13/test5.html"
		}, {
			"name": "test6",
			"url": "html/ch13/test6.html"
		}, {
			"name": "test7",
			"url": "html/ch13/test7.html"
		}, {
			"name": "test8",
			"url": "html/ch13/test8.html"
		}, {
			"name": "test9",
			"url": "html/ch13/test9.html"
		}, {
			"name": "test10",
			"url": "html/ch13/test10.html"
		}, {
			"name": "test11",
			"url": "html/ch13/test11.html"
		}, {
			"name": "test12",
			"url": "html/ch13/test12.html"
		}, {
			"name": "test13",
			"url": "html/ch13/test13.html"
		}, {
			"name": "test14",
			"url": "html/ch13/test14.html"
		}, {
			"name": "test15",
			"url": "html/ch13/test15.html"
		}, {
			"name": "test16",
			"url": "html/ch13/test16.html"
		}, {
			"name": "test18",
			"url": "html/ch13/test18.html"
		}, {
			"name": "test19",
			"url": "html/ch13/test19.html"
		}, {
			"name": "test20",
			"url": "html/ch13/test20.html"
		}, {
			"name": "test21",
			"url": "html/ch13/test21.html"
		}, {
			"name": "test22",
			"url": "html/ch13/test22.html"
		}, {
			"name": "test23",
			"url": "html/ch13/test23.html"
		}]
	}, {
		"name": "ch14-javascript-BOM(浏览器对象)",
		"children": [{
			"name": "test1",
			"url": "html/ch14/test1.html"
		}, {
			"name": "test2",
			"url": "html/ch14/test2.html"
		}, {
			"name": "test3",
			"url": "html/ch14/test3.html"
		}, {
			"name": "test4",
			"url": "html/ch14/test4.html"
		}, {
			"name": "test5",
			"url": "html/ch14/test5.html"
		}, {
			"name": "test6",
			"url": "html/ch14/test6.html"
		}, {
			"name": "test7",
			"url": "html/ch14/test7.html"
		}, {
			"name": "test8",
			"url": "html/ch14/test8.html"
		}, {
			"name": "test9",
			"url": "html/ch14/test9.html"
		}, {
			"name": "test10",
			"url": "html/ch14/test10.html"
		}, {
			"name": "test11",
			"url": "html/ch14/test11.html"
		}, {
			"name": "test12",
			"url": "html/ch14/test12.html"
		}, {
			"name": "test13",
			"url": "html/ch14/test13.html"
		}, {
			"name": "test14",
			"url": "html/ch14/test14.html"
		}, {
			"name": "test15",
			"url": "html/ch14/test15.html"
		}, {
			"name": "test16",
			"url": "html/ch14/test16.html"
		}, {
			"name": "test17",
			"url": "html/ch14/test17.html"
		}]
	}, {
		"name": "ch15-javascript-DOM(文档对象模型)",
		"children": [{
			"name": "test1",
			"url": "html/ch15/test1.html"
		}, {
			"name": "test2",
			"url": "html/ch15/test2.html"
		}, {
			"name": "test3",
			"url": "html/ch15/test3.html"
		}, {
			"name": "test4",
			"url": "html/ch15/test4.html"
		}, {
			"name": "test5",
			"url": "html/ch15/test5.html"
		}, {
			"name": "test6",
			"url": "html/ch15/test6.html"
		}, {
			"name": "test7",
			"url": "html/ch15/test7.html"
		}, {
			"name": "test8",
			"url": "html/ch15/test8.html"
		}, {
			"name": "test9",
			"url": "html/ch15/test9.html"
		}, {
			"name": "test10",
			"url": "html/ch15/test10.html"
		}, {
			"name": "test11",
			"url": "html/ch15/test11.html"
		}, {
			"name": "test12",
			"url": "html/ch15/test12.html"
		}, {
			"name": "test13",
			"url": "html/ch15/test13.html"
		}, {
			"name": "test14",
			"url": "html/ch15/test14.html"
		}, {
			"name": "test15",
			"url": "html/ch15/test15.html"
		}, {
			"name": "test16",
			"url": "html/ch15/test16.html"
		}, {
			"name": "test17",
			"url": "html/ch15/test17.html"
		}, {
			"name": "test18",
			"url": "html/ch15/test18.html"
		}, {
			"name": "test19",
			"url": "html/ch15/test19.html"
		}, {
			"name": "test20",
			"url": "html/ch15/test20.html"
		}, {
			"name": "test21",
			"url": "html/ch15/test21.html"
		}, {
			"name": "test22",
			"url": "html/ch15/test22.html"
		}, {
			"name": "test23",
			"url": "html/ch15/test23.html"
		}]
	}, {
		"name": "没有子节点",
		"isParent": true
	}]
}, {
	"name": "教程",
	"icon": "css/ztree.3.5.26/zTreeStyle/img/diy/2.png",
	"children": [{
		"name": "ch2-html标签1",
		"url": "html/tech/ch2.html"
	}, {
		"name": "ch3-html标签-表格，列表",
		"url": "html/tech/ch3.html"
	}, {
		"name": "ch4-html标签-表单-输入",
		"url": "html/tech/ch4.html"
	}, {
		"name": "ch5-css选择器，权重",
		"url": "html/tech/ch5.html"
	}, {
		"name": "ch6-css排版，盒子模型",
		"url": "html/tech/ch6.html"
	}, {
		"name": "ch7-css布局小技巧",
		"url": "html/tech/ch7.html"
	}, {
		"name": "ch8-css布局",
		"url": "html/tech/ch8.html"
	}, {
		"name": "ch9-javascript-基本",
		"url": "html/tech/ch9.html"
	}, {
		"name": "ch10-javascript-基础",
		"url": "html/tech/ch10.html"
	}, {
		"name": "ch11-javascript-数组与流程控制",
		"url": "html/tech/ch11.html"
	}, {
		"name": "ch12-javascript-函数与事件",
		"url": "html/tech/ch12.html"
	}, {
		"name": "ch13-javascript-内置对象",
		"url": "html/tech/ch13.html"
	}, {
		"name": "ch14-javascript-BOM(浏览器对象)",
		"url": "html/tech/ch14.html"
	}, {
		"name": "ch15-javascript-DOM(文档对象模型)",
		"url": "html/tech/ch15.html"
	}, {
		"name": "jquery教程",
		"children": [{
			"name": "jquery样式",
			"url": "html/tech/jquery_style.html"
		}, {
			"name": "jqueryDOM",
			"url": "html/tech/jquery_DOM.html"
		}, {
			"name": "jquery事件",
			"url": "html/tech/jquery_event.html"
		}]
	}, {
		"name": "计算绩点",
		"url": "html/tech/testG.html"
	}, {
		"name": "web前端知识结构",
		"icon": "css/ztree.3.5.26/zTreeStyle/img/diy/Organization_structure_16px.png",
		"url": "html/tech/front.html"
	}, {
		"name": "JavaScript实例",
		"children": [{
			"name": "基础",
			"children": [{
				"name": "用JavaScript输出文本",
				"url": "js_demo/t1_base/test1.html"
			}, {
				"name": "用JavaScript改变HTML元素",
				"url": "js_demo/t1_base/test2.html"
			}, {
				"name": "一个外部JavaScript",
				"url": "js_demo/t1_base/test3.html"
			}]
		}, {
			"name": "注释",
			"children": [{
				"name": "JavaScript 语句",
				"url": "js_demo/t2_annotation/test1.html"
			}, {
				"name": "JavaScript 代码块",
				"url": "js_demo/t2_annotation/test2.html"
			}, {
				"name": "JavaScript 单行注释",
				"url": "js_demo/t2_annotation/test3.html"
			}, {
				"name": "JavaScript 多行注释",
				"url": "js_demo/t2_annotation/test4.html"
			}]
		}, {
			"name": "变量",
			"children": [{
				"name": "声明一个变量，为它赋值，然后显示出来",
				"url": "js_demo/t3_variable/test1.html"
			}]
		}, {
			"name": "条件表达式",
			"children": [{
				"name": "If 语句",
				"url": "js_demo/t4_conditional/test1.html"
			}, {
				"name": "If...else 语句",
				"url": "js_demo/t4_conditional/test2.html"
			}, {
				"name": "if..else if...else 语句",
				"url": "js_demo/t4_conditional/test3.html"
			}, {
				"name": "随机链接",
				"url": "js_demo/t4_conditional/test4.html"
			}, {
				"name": "Switch 语句",
				"url": "js_demo/t4_conditional/test5.html"
			}]
		}, {
			"name": "循环",
			"children": [{
				"name": "For 循环",
				"url": "js_demo/t5_circulation/test1.html"
			}, {
				"name": "循环输出 HTML 标题",
				"url": "js_demo/t5_circulation/test2.html"
			}, {
				"name": "While 循环",
				"url": "js_demo/t5_circulation/test3.html"
			}, {
				"name": "do While 循环",
				"url": "js_demo/t5_circulation/test4.html"
			}, {
				"name": "break 语句",
				"url": "js_demo/t5_circulation/test5.html"
			}, {
				"name": "使用 For...In 声明来遍历数组内的元素",
				"url": "js_demo/t5_circulation/test6.html"
			}, {
				"name": "continue 语句",
				"url": "js_demo/t5_circulation/test7.html"
			}]
		}, {
			"name": "函数（方法）",
			"children": [{
				"name": "第一个函数",
				"url": "js_demo/t6_function/test1.html"
			}, {
				"name": "带有参数的函数",
				"url": "js_demo/t6_function/test2.html"
			}, {
				"name": "带有参数的函数 2",
				"url": "js_demo/t6_function/test3.html"
			}, {
				"name": "返回值的函数",
				"url": "js_demo/t6_function/test4.html"
			}, {
				"name": "带有参数并返回值的函数",
				"url": "js_demo/t6_function/test5.html"
			}]
		}, {
			"name": "消息框",
			"children": [{
				"name": "Alert(警告)框",
				"url": "js_demo/t7_msgbox/test1.html"
			}, {
				"name": "带有换行的警告框",
				"url": "js_demo/t7_msgbox/test2.html"
			}, {
				"name": "确认框",
				"url": "js_demo/t7_msgbox/test3.html"
			}, {
				"name": "提示框",
				"url": "js_demo/t7_msgbox/test4.html"
			}]
		}, {
			"name": "网页事件",
			"children": [{
				"name": "onclick事件",
				"url": "js_demo/t8_event/test1.html"
			}, {
				"name": "onload事件",
				"url": "js_demo/t8_event/test2.html"
			}, {
				"name": "onchange 事件",
				"url": "js_demo/t8_event/test3.html"
			}, {
				"name": "onmouseover 和 onmouseout 事件",
				"url": "js_demo/t8_event/test4.html"
			}, {
				"name": "onmousedown、onmouseup",
				"url": "js_demo/t8_event/test5.html"
			}, {
				"name": "onfocus",
				"url": "js_demo/t8_event/test6.html"
			}, {
				"name": "onblur 事件",
				"url": "js_demo/t8_event/test7.html"
			}, {
				"name": "ondblclick 事件",
				"url": "js_demo/t8_event/test8.html"
			}, {
				"name": "onselect 事件",
				"url": "js_demo/t8_event/test9.html"
			}, {
				"name": "onkeydown 事件",
				"url": "js_demo/t8_event/test10.html"
			}, {
				"name": "onkeypress 事件",
				"url": "js_demo/t8_event/test11.html"
			}, {
				"name": "onkeyup 事件",
				"url": "js_demo/t8_event/test12.html"
			}]
		}, {
			"name": "错误与异常",
			"children": [{
				"name": "try...catch 语句",
				"url": "js_demo/t9_error/test1.html"
			}, {
				"name": "带有确认框的 try...catch 语句",
				"url": "js_demo/t9_error/test2.html"
			}, {
				"name": "onerror 事件",
				"url": "js_demo/t9_error/test3.html"
			}]
		}, {
			"name": "高级",
			"children": [{
				"name": "cookie",
				"url": "js_demo/t10_advanced/test1.html"
			}, {
				"name": "简单的计时",
				"url": "js_demo/t10_advanced/test2.html"
			}, {
				"name": "另一个简单的计时",
				"url": "js_demo/t10_advanced/test3.html"
			}, {
				"name": "在一个无穷循环中的计时事件",
				"url": "js_demo/t10_advanced/test4.html"
			}, {
				"name": "带有停止按钮的无穷循环中的计时事件",
				"url": "js_demo/t10_advanced/test5.html"
			}, {
				"name": "使用计时事件制作的钟表",
				"url": "js_demo/t10_advanced/test6.html"
			}, {
				"name": "创建对象的实例",
				"url": "js_demo/t10_advanced/test7.html"
			}, {
				"name": "创建用于对象的模板",
				"url": "js_demo/t10_advanced/test8.html"
			}, {
				"name": "检测浏览器的全部信息",
				"url": "js_demo/t10_advanced/test9.html"
			}]
		}, {
			"name": "字符串String对象",
			"children": [{
				"name": "返回字符串的长度",
				"url": "js_demo/t11_string/test1.html"
			}, {
				"name": "为字符串添加样式",
				"url": "js_demo/t11_string/test2.html"
			}, {
				"name": "返回字符串中指定文本首次出现的位置",
				"url": "js_demo/t11_string/test3.html"
			}, {
				"name": "查找字符串中特定的字符",
				"url": "js_demo/t11_string/test4.html"
			}, {
				"name": "替换字符串中的字符",
				"url": "js_demo/t11_string/test5.html"
			}]
		}]
	}]
}, {
	"name": "学生项目",
	"icon": "css/ztree.3.5.26/zTreeStyle/img/diy/student_girl_light_16px.png",
	"children": [{
		"name": "蒙班",
		"icon": "css/ztree.3.5.26/zTreeStyle/img/diy/Horse_16px.png",
		"children": [ {
			"name": "20142104388李特日格乐",
			"url": "html/stu/meng/20142104388/index.html"
		}]
	}, {
		"name": "汉班",
		"icon": "css/ztree.3.5.26/zTreeStyle/img/diy/cow_ox_bull_cattle_16px.png",
		"children": [{
			"name": "20141101985张晓焕",
			"url": "20141101985张晓焕"
		}, {
			"name": "20141103219孙玉莹",
			"url": "20141103219孙玉莹"
		}, {
			"name": "20141103220王艳茹",
			"url": "20141103220王艳茹"
		}, {
			"name": "20141103221格日勒",
			"url": "20141103221格日勒"
		}, {
			"name": "20141103222李万婧",
			"url": "20141103222李万婧"
		}, {
			"name": "20141103223吴萨仁格日乐",
			"url": "20141103223吴萨仁格日乐"
		}, {
			"name": "20141103224王宇祯",
			"url": "20141103224王宇祯"
		}, {
			"name": "20141103225于双源",
			"url": "20141103225于双源"
		}, {
			"name": "20141103226张聪",
			"url": "20141103226张聪"
		}, {
			"name": "20141103227王欣悦",
			"url": "20141103227王欣悦"
		}, {
			"name": "20141103228孙婉贞",
			"url": "20141103228孙婉贞"
		}, {
			"name": "20141103229李昕容",
			"url": "20141103229李昕容"
		}, {
			"name": "20141103230辛羽",
			"url": "20141103230辛羽"
		}, {
			"name": "20141103231程璐",
			"url": "20141103231程璐"
		}, {
			"name": "20141103232李天骄",
			"url": "20141103232李天骄"
		}, {
			"name": "20141103233燕丽萍",
			"url": "20141103233燕丽萍"
		}, {
			"name": "20141103234安溪露",
			"url": "20141103234安溪露"
		}, {
			"name": "20141103235郭建强",
			"url": "20141103235郭建强"
		}, {
			"name": "20141103236于浩华",
			"url": "20141103236于浩华"
		}, {
			"name": "20141103237李静文",
			"url": "20141103237李静文"
		}, {
			"name": "20141103238张燕鸿",
			"url": "20141103238张燕鸿"
		}, {
			"name": "20141103239王艳玲",
			"url": "20141103239王艳玲"
		}, {
			"name": "20141103241李佳璐",
			"url": "20141103241李佳璐"
		}, {
			"name": "20141103242王善舆",
			"url": "20141103242王善舆"
		}, {
			"name": "20141103243侯俊臣",
			"url": "20141103243侯俊臣"
		}, {
			"name": "20141103244肖鹏影",
			"url": "20141103244肖鹏影"
		}, {
			"name": "20141103245张晗",
			"url": "20141103245张晗"
		}, {
			"name": "20141103246沈素平",
			"url": "20141103246沈素平"
		}, {
			"name": "20141103247刘璐璐",
			"url": "20141103247刘璐璐"
		}, {
			"name": "20141103248刘娜",
			"url": "20141103248刘娜"
		}, {
			"name": "20141103249李梦雪",
			"url": "20141103249李梦雪"
		}, {
			"name": "20141103250张永臻",
			"url": "20141103250张永臻"
		}, {
			"name": "20141103251王佳星",
			"url": "20141103251王佳星"
		}, {
			"name": "20141103252赵帅",
			"url": "20141103252赵帅"
		}, {
			"name": "20141103253王晴",
			"url": "20141103253王晴"
		}, {
			"name": "20141105872黄向英",
			"url": "20141105872黄向英"
		}, {
			"name": "20141105873邓辉",
			"url": "20141105873邓辉"
		}, {
			"name": "20141105874吴月艺",
			"url": "20141105874吴月艺"
		}, {
			"name": "20141105875李阳月",
			"url": "20141105875李阳月"
		}, {
			"name": "20141105911赵雅楠",
			"url": "20141105911赵雅楠"
		}, {
			"name": "20141105912韩倩倩",
			"url": "20141105912韩倩倩"
		}, {
			"name": "20141105913高晓娜",
			"url": "20141105913高晓娜"
		}, {
			"name": "20141105914邵春节",
			"url": "20141105914邵春节"
		}, {
			"name": "20141105915李欣",
			"url": "20141105915李欣"
		}, {
			"name": "20141106016柳璇",
			"url": "20141106016柳璇"
		}, {
			"name": "20141106017张泽凌",
			"url": "20141106017张泽凌"
		}, {
			"name": "20141106018张贺",
			"url": "20141106018张贺"
		}, {
			"name": "20141106019王雨薇",
			"url": "20141106019王雨薇"
		}, {
			"name": "20141106020董苗苗",
			"url": "20141106020董苗苗"
		}]
	}]
}, {
	"name": "点名",
	"icon": "css/ztree.3.5.26/zTreeStyle/img/diy/8.png",
	"children": [{
		"name": "汉班点名",
		"url": "dianming.html"
	}, {
		"name": "蒙班点名",
		"url": "dianming2.html"
	}]
}, {
	"name": "相关学习网站",
	"icon": "css/ztree.3.5.26/zTreeStyle/img/diy/Chrome_11_16px.png",
	"children": [{
		"name": "菜鸟教程",
		"url": "http://www.runoob.com/"
	}, {
		"name": "w3school",
		"url": "http://www.w3school.com.cn/"
	}, {
		"name": "课程源码",
		"url": "https://github.com/wl664125833/tech"
	}]
}, {
	"name": "游戏",
	"icon": "css/ztree.3.5.26/zTreeStyle/img/diy/Game.png",
	"children": [{
		"name": "打砖块",
		"url": "html/game/brick/index.html"
	}, {
		"name": "迷宫",
		"url": "html/game/maze/index.html"
	}, {
		"name": "数独",
		"url": "html/game/soduku/soduku.html"
	}, {
		"name": "2048",
		"url": "html/game/2048/2048.html"
	}, {
		"name": "扫雷",
		"url": "html/game/mine/mine.html"
	}, {
		"name": "贪吃蛇",
		"url": "html/game/snake/snake.html"
	}]
}]